
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.craftnotaizai.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.DoubleHighBlockItem;
import net.minecraft.world.item.BlockItem;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.client.renderer.item.ItemProperties;

import net.mcreator.craftnotaizai.item.ZeldrisSwordItem;
import net.mcreator.craftnotaizai.item.WhipItem;
import net.mcreator.craftnotaizai.item.WeinheidtArmorItem;
import net.mcreator.craftnotaizai.item.VivianArmorItem;
import net.mcreator.craftnotaizai.item.UncookedDuskItem;
import net.mcreator.craftnotaizai.item.TyrantDragonMeatItem;
import net.mcreator.craftnotaizai.item.TyrantDragonCookedMeatItem;
import net.mcreator.craftnotaizai.item.TwinBowHerrittItem;
import net.mcreator.craftnotaizai.item.TwigoswordItem;
import net.mcreator.craftnotaizai.item.TwigoArmorItem;
import net.mcreator.craftnotaizai.item.TrollEarItem;
import net.mcreator.craftnotaizai.item.TentaclesItem;
import net.mcreator.craftnotaizai.item.TeleportationOrbItem;
import net.mcreator.craftnotaizai.item.SwordWolfFurItem;
import net.mcreator.craftnotaizai.item.StaffOfImprisonmentItem;
import net.mcreator.craftnotaizai.item.SpiraledlanceItem;
import net.mcreator.craftnotaizai.item.SoldierArmorItem;
import net.mcreator.craftnotaizai.item.SladerArmorItem;
import net.mcreator.craftnotaizai.item.SimonArmorItem;
import net.mcreator.craftnotaizai.item.SevenDeadlySinsOpeningItem;
import net.mcreator.craftnotaizai.item.SerpentIconItem;
import net.mcreator.craftnotaizai.item.SequenceItem;
import net.mcreator.craftnotaizai.item.ScytheItem;
import net.mcreator.craftnotaizai.item.SawSwordItem;
import net.mcreator.craftnotaizai.item.SawBladeItem;
import net.mcreator.craftnotaizai.item.RuinArmorItem;
import net.mcreator.craftnotaizai.item.RoyalknightItem;
import net.mcreator.craftnotaizai.item.RhittaItem;
import net.mcreator.craftnotaizai.item.ReposeIconItem;
import net.mcreator.craftnotaizai.item.RedKnightArmorItem;
import net.mcreator.craftnotaizai.item.ReaperScytheItem;
import net.mcreator.craftnotaizai.item.ReRollMagicItem;
import net.mcreator.craftnotaizai.item.RapierItem;
import net.mcreator.craftnotaizai.item.RankItem;
import net.mcreator.craftnotaizai.item.PigIconItem;
import net.mcreator.craftnotaizai.item.PerfectCubeOrbItem;
import net.mcreator.craftnotaizai.item.PeaceAmuletItem;
import net.mcreator.craftnotaizai.item.ParadaArmorItem;
import net.mcreator.craftnotaizai.item.NeedleItem;
import net.mcreator.craftnotaizai.item.MuramoArmorItem;
import net.mcreator.craftnotaizai.item.MugAleItem;
import net.mcreator.craftnotaizai.item.MonsterBlockItem;
import net.mcreator.craftnotaizai.item.MinimumTabletsItem;
import net.mcreator.craftnotaizai.item.MidTierSoulsItem;
import net.mcreator.craftnotaizai.item.MerlinOutfitItem;
import net.mcreator.craftnotaizai.item.MerlinArmorChestPlateItem;
import net.mcreator.craftnotaizai.item.MeliodasoutfitItem;
import net.mcreator.craftnotaizai.item.MeliodasdanaforarmorItem;
import net.mcreator.craftnotaizai.item.MeliodasBoarHatItem;
import net.mcreator.craftnotaizai.item.MeliodasArmorItem;
import net.mcreator.craftnotaizai.item.MagicScrollItem;
import net.mcreator.craftnotaizai.item.LuminosityItem;
import net.mcreator.craftnotaizai.item.LumeOrbItem;
import net.mcreator.craftnotaizai.item.LowTierSoulsItem;
import net.mcreator.craftnotaizai.item.LostvayneItem;
import net.mcreator.craftnotaizai.item.LongAxeItem;
import net.mcreator.craftnotaizai.item.LizSwordItem;
import net.mcreator.craftnotaizai.item.LizSneathSwordItem;
import net.mcreator.craftnotaizai.item.KnightarmorItem;
import net.mcreator.craftnotaizai.item.KingsArmorItem;
import net.mcreator.craftnotaizai.item.KingOutfitItem;
import net.mcreator.craftnotaizai.item.KatanaItem;
import net.mcreator.craftnotaizai.item.JillianArmorItem;
import net.mcreator.craftnotaizai.item.JerichoarmorItem;
import net.mcreator.craftnotaizai.item.JerichoSwordItem;
import net.mcreator.craftnotaizai.item.JerichoItem;
import net.mcreator.craftnotaizai.item.HyperRecoveryItem;
import net.mcreator.craftnotaizai.item.HugoArmorItem;
import net.mcreator.craftnotaizai.item.HowzerArmorOutfitItem;
import net.mcreator.craftnotaizai.item.HowzerArmorItem;
import net.mcreator.craftnotaizai.item.HolyTreeShardItem;
import net.mcreator.craftnotaizai.item.HolyStaffCoureChouseItem;
import net.mcreator.craftnotaizai.item.HighTierSoulsItem;
import net.mcreator.craftnotaizai.item.HendriksonSwordItem;
import net.mcreator.craftnotaizai.item.HendricksonArmorItem;
import net.mcreator.craftnotaizai.item.HelbrumswordItem;
import net.mcreator.craftnotaizai.item.HelbrumArmorItem;
import net.mcreator.craftnotaizai.item.HeatForkItem;
import net.mcreator.craftnotaizai.item.HalbertItem;
import net.mcreator.craftnotaizai.item.GustafArmorItem;
import net.mcreator.craftnotaizai.item.GuilaArmorItem;
import net.mcreator.craftnotaizai.item.GuilaArmor2Item;
import net.mcreator.craftnotaizai.item.GuardSpearItem;
import net.mcreator.craftnotaizai.item.GreenKnightArmorItem;
import net.mcreator.craftnotaizai.item.GrayDemonBloodNeedleItem;
import net.mcreator.craftnotaizai.item.GowtherOutfitItem;
import net.mcreator.craftnotaizai.item.GowtherArmorS2Item;
import net.mcreator.craftnotaizai.item.GowtherArmorItem;
import net.mcreator.craftnotaizai.item.GolgiusarmorItem;
import net.mcreator.craftnotaizai.item.GolgiusSwordItem;
import net.mcreator.craftnotaizai.item.GoddessAmberShardItem;
import net.mcreator.craftnotaizai.item.GoddessAmberItem;
import net.mcreator.craftnotaizai.item.GoatIconItem;
import net.mcreator.craftnotaizai.item.GlowMugItem;
import net.mcreator.craftnotaizai.item.GilThunderSwordItem;
import net.mcreator.craftnotaizai.item.GilThunderArmorItem;
import net.mcreator.craftnotaizai.item.GideonItem;
import net.mcreator.craftnotaizai.item.FriesiaarmorItem;
import net.mcreator.craftnotaizai.item.FragmentOfEternalDarknessItem;
import net.mcreator.craftnotaizai.item.FragmentOfEternalDarkness3Item;
import net.mcreator.craftnotaizai.item.FragmentOfEternalDarkness2Item;
import net.mcreator.craftnotaizai.item.FoxIconItem;
import net.mcreator.craftnotaizai.item.FountainOfYouthItem;
import net.mcreator.craftnotaizai.item.FlyingSaucerItem;
import net.mcreator.craftnotaizai.item.FairyHelbramArmorItem;
import net.mcreator.craftnotaizai.item.EscanorTavernItem;
import net.mcreator.craftnotaizai.item.EscanorArmorItem;
import net.mcreator.craftnotaizai.item.EmptyorbItem;
import net.mcreator.craftnotaizai.item.EmptyNeedleItem;
import net.mcreator.craftnotaizai.item.EmptyMugItem;
import net.mcreator.craftnotaizai.item.ElaineArmorItem;
import net.mcreator.craftnotaizai.item.EarthCrawlerTailItem;
import net.mcreator.craftnotaizai.item.EarthCrawlerTailCookedItem;
import net.mcreator.craftnotaizai.item.DreyfusSwordItem;
import net.mcreator.craftnotaizai.item.DreyfusArmorItem;
import net.mcreator.craftnotaizai.item.DragonIconItem;
import net.mcreator.craftnotaizai.item.DragonHandleItem;
import net.mcreator.craftnotaizai.item.DoubleSidedSpearItem;
import net.mcreator.craftnotaizai.item.DianeoutfitItem;
import net.mcreator.craftnotaizai.item.DianeArmorItem;
import net.mcreator.craftnotaizai.item.DemonWingItem;
import net.mcreator.craftnotaizai.item.DemonKingSwordItem;
import net.mcreator.craftnotaizai.item.DemonClawItem;
import net.mcreator.craftnotaizai.item.DemonBloodItem;
import net.mcreator.craftnotaizai.item.DemonAxeItem;
import net.mcreator.craftnotaizai.item.CurvedSwordItem;
import net.mcreator.craftnotaizai.item.CookedtentaclesItem;
import net.mcreator.craftnotaizai.item.CookedDuskMeatItem;
import net.mcreator.craftnotaizai.item.CookedAngleMeatItem;
import net.mcreator.craftnotaizai.item.CookTrollEarItem;
import net.mcreator.craftnotaizai.item.CoffinOfEternalDarknessItem;
import net.mcreator.craftnotaizai.item.CiderMugItem;
import net.mcreator.craftnotaizai.item.ChickenMatangoMushRoomItem;
import net.mcreator.craftnotaizai.item.Chastiefol2Item;
import net.mcreator.craftnotaizai.item.CarbonSteelItem;
import net.mcreator.craftnotaizai.item.CainArmorItem;
import net.mcreator.craftnotaizai.item.BritanniaCoinsItem;
import net.mcreator.craftnotaizai.item.BowItem;
import net.mcreator.craftnotaizai.item.BoarHatOutfitItem;
import net.mcreator.craftnotaizai.item.BellStaffItem;
import net.mcreator.craftnotaizai.item.BeerMugItem;
import net.mcreator.craftnotaizai.item.BearIconItem;
import net.mcreator.craftnotaizai.item.BasquiasItem;
import net.mcreator.craftnotaizai.item.BanOutfitItem;
import net.mcreator.craftnotaizai.item.BanArmorS2Item;
import net.mcreator.craftnotaizai.item.BanArmorItem;
import net.mcreator.craftnotaizai.item.BalorsMagicalEyeItem;
import net.mcreator.craftnotaizai.item.BakeApplePieItem;
import net.mcreator.craftnotaizai.item.Axe2Item;
import net.mcreator.craftnotaizai.item.ArtherArmorItem;
import net.mcreator.craftnotaizai.item.ApplepieItem;
import net.mcreator.craftnotaizai.item.AngleCureMeatItem;
import net.mcreator.craftnotaizai.item.AndreArmorItem;
import net.mcreator.craftnotaizai.item.AldanItem;
import net.mcreator.craftnotaizai.item.AgaveSeedsItem;
import net.mcreator.craftnotaizai.item.AgaveItem;
import net.mcreator.craftnotaizai.block.display.RhittaBlockDisplayItem;
import net.mcreator.craftnotaizai.CraftNoTaizaiMod;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
public class CraftNoTaizaiModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, CraftNoTaizaiMod.MODID);
	public static final RegistryObject<Item> DRAGON_HANDLE = REGISTRY.register("dragon_handle", () -> new DragonHandleItem());
	public static final RegistryObject<Item> RHITTA = REGISTRY.register("rhitta", () -> new RhittaItem());
	public static final RegistryObject<Item> CHASTIEFOL_2 = REGISTRY.register("chastiefol_2", () -> new Chastiefol2Item());
	public static final RegistryObject<Item> POLLEN_GARDEN_SPAWN_EGG = REGISTRY.register("pollen_garden_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.POLLEN_GARDEN, -10027264, -13369600, new Item.Properties()));
	public static final RegistryObject<Item> LUMINOSITY = REGISTRY.register("luminosity", () -> new LuminosityItem());
	public static final RegistryObject<Item> SUNFLOWER_SPAWN_EGG = REGISTRY.register("sunflower_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.SUNFLOWER, -9175175, -2097408, new Item.Properties()));
	public static final RegistryObject<Item> DEMON_BLOOD = REGISTRY.register("demon_blood", () -> new DemonBloodItem());
	public static final RegistryObject<Item> GLOW_BLOCK = block(CraftNoTaizaiModBlocks.GLOW_BLOCK);
	public static final RegistryObject<Item> DEMON_AXE = REGISTRY.register("demon_axe", () -> new DemonAxeItem());
	public static final RegistryObject<Item> DEMON_WING = REGISTRY.register("demon_wing", () -> new DemonWingItem());
	public static final RegistryObject<Item> UNCOOKED_DUSK = REGISTRY.register("uncooked_dusk", () -> new UncookedDuskItem());
	public static final RegistryObject<Item> COOKED_DUSK_MEAT = REGISTRY.register("cooked_dusk_meat", () -> new CookedDuskMeatItem());
	public static final RegistryObject<Item> TENTACLES = REGISTRY.register("tentacles", () -> new TentaclesItem());
	public static final RegistryObject<Item> COOKEDTENTACLES = REGISTRY.register("cookedtentacles", () -> new CookedtentaclesItem());
	public static final RegistryObject<Item> GIDEON = REGISTRY.register("gideon", () -> new GideonItem());
	public static final RegistryObject<Item> ALDAN = REGISTRY.register("aldan", () -> new AldanItem());
	public static final RegistryObject<Item> MANTA_SPAWN_EGG = REGISTRY.register("manta_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.MANTA, -10588791, -983, new Item.Properties()));
	public static final RegistryObject<Item> LIZ_SWORD = REGISTRY.register("liz_sword", () -> new LizSwordItem());
	public static final RegistryObject<Item> LIZ_SNEATH_SWORD = REGISTRY.register("liz_sneath_sword", () -> new LizSneathSwordItem());
	public static final RegistryObject<Item> GIL_THUNDER_ARMOR_CHESTPLATE = REGISTRY.register("gil_thunder_armor_chestplate", () -> new GilThunderArmorItem.Chestplate());
	public static final RegistryObject<Item> GIL_THUNDER_ARMOR_LEGGINGS = REGISTRY.register("gil_thunder_armor_leggings", () -> new GilThunderArmorItem.Leggings());
	public static final RegistryObject<Item> CHICKEN_SPAWN_EGG = REGISTRY.register("chicken_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.CHICKEN, -10066177, -39322, new Item.Properties()));
	public static final RegistryObject<Item> LOSTVAYNE = REGISTRY.register("lostvayne", () -> new LostvayneItem());
	public static final RegistryObject<Item> TWIN_BOW_HERRITT = REGISTRY.register("twin_bow_herritt", () -> new TwinBowHerrittItem());
	public static final RegistryObject<Item> GECKOLIB_KRAKEN_SPAWN_EGG = REGISTRY.register("geckolib_kraken_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GECKOLIB_KRAKEN, -154, -1, new Item.Properties()));
	public static final RegistryObject<Item> DEMON_CLAW = REGISTRY.register("demon_claw", () -> new DemonClawItem());
	public static final RegistryObject<Item> HELBRUM_ARMOR_CHESTPLATE = REGISTRY.register("helbrum_armor_chestplate", () -> new HelbrumArmorItem.Chestplate());
	public static final RegistryObject<Item> HELBRUM_ARMOR_LEGGINGS = REGISTRY.register("helbrum_armor_leggings", () -> new HelbrumArmorItem.Leggings());
	public static final RegistryObject<Item> RED_DEMON_GECKOLIB_SPAWN_EGG = REGISTRY.register("red_demon_geckolib_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.RED_DEMON_GECKOLIB, -65536, -6750004, new Item.Properties()));
	public static final RegistryObject<Item> HOWZER_ARMOR_CHESTPLATE = REGISTRY.register("howzer_armor_chestplate", () -> new HowzerArmorItem.Chestplate());
	public static final RegistryObject<Item> HOWZER_ARMOR_LEGGINGS = REGISTRY.register("howzer_armor_leggings", () -> new HowzerArmorItem.Leggings());
	public static final RegistryObject<Item> SLADER_ARMOR_HELMET = REGISTRY.register("slader_armor_helmet", () -> new SladerArmorItem.Helmet());
	public static final RegistryObject<Item> SLADER_ARMOR_CHESTPLATE = REGISTRY.register("slader_armor_chestplate", () -> new SladerArmorItem.Chestplate());
	public static final RegistryObject<Item> SLADER_ARMOR_LEGGINGS = REGISTRY.register("slader_armor_leggings", () -> new SladerArmorItem.Leggings());
	public static final RegistryObject<Item> GUARDIAN_1_SPAWN_EGG = REGISTRY.register("guardian_1_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GUARDIAN_1, -13382656, -10027264, new Item.Properties()));
	public static final RegistryObject<Item> BAN_OUTFIT_HELMET = REGISTRY.register("ban_outfit_helmet", () -> new BanOutfitItem.Helmet());
	public static final RegistryObject<Item> BAN_OUTFIT_CHESTPLATE = REGISTRY.register("ban_outfit_chestplate", () -> new BanOutfitItem.Chestplate());
	public static final RegistryObject<Item> BAN_OUTFIT_LEGGINGS = REGISTRY.register("ban_outfit_leggings", () -> new BanOutfitItem.Leggings());
	public static final RegistryObject<Item> KING_OUTFIT_CHESTPLATE = REGISTRY.register("king_outfit_chestplate", () -> new KingOutfitItem.Chestplate());
	public static final RegistryObject<Item> KING_OUTFIT_LEGGINGS = REGISTRY.register("king_outfit_leggings", () -> new KingOutfitItem.Leggings());
	public static final RegistryObject<Item> MERLIN_OUTFIT_CHESTPLATE = REGISTRY.register("merlin_outfit_chestplate", () -> new MerlinOutfitItem.Chestplate());
	public static final RegistryObject<Item> MERLIN_OUTFIT_LEGGINGS = REGISTRY.register("merlin_outfit_leggings", () -> new MerlinOutfitItem.Leggings());
	public static final RegistryObject<Item> MELIODASOUTFIT_CHESTPLATE = REGISTRY.register("meliodasoutfit_chestplate", () -> new MeliodasoutfitItem.Chestplate());
	public static final RegistryObject<Item> MELIODASOUTFIT_LEGGINGS = REGISTRY.register("meliodasoutfit_leggings", () -> new MeliodasoutfitItem.Leggings());
	public static final RegistryObject<Item> ARTHER_ARMOR_CHESTPLATE = REGISTRY.register("arther_armor_chestplate", () -> new ArtherArmorItem.Chestplate());
	public static final RegistryObject<Item> ARTHER_ARMOR_LEGGINGS = REGISTRY.register("arther_armor_leggings", () -> new ArtherArmorItem.Leggings());
	public static final RegistryObject<Item> GOWTHER_OUTFIT_CHESTPLATE = REGISTRY.register("gowther_outfit_chestplate", () -> new GowtherOutfitItem.Chestplate());
	public static final RegistryObject<Item> GOWTHER_OUTFIT_LEGGINGS = REGISTRY.register("gowther_outfit_leggings", () -> new GowtherOutfitItem.Leggings());
	public static final RegistryObject<Item> DIANEOUTFIT_CHESTPLATE = REGISTRY.register("dianeoutfit_chestplate", () -> new DianeoutfitItem.Chestplate());
	public static final RegistryObject<Item> DIANEOUTFIT_LEGGINGS = REGISTRY.register("dianeoutfit_leggings", () -> new DianeoutfitItem.Leggings());
	public static final RegistryObject<Item> JERICHOARMOR_CHESTPLATE = REGISTRY.register("jerichoarmor_chestplate", () -> new JerichoarmorItem.Chestplate());
	public static final RegistryObject<Item> JERICHOARMOR_LEGGINGS = REGISTRY.register("jerichoarmor_leggings", () -> new JerichoarmorItem.Leggings());
	public static final RegistryObject<Item> MELIODASDANAFORARMOR_CHESTPLATE = REGISTRY.register("meliodasdanaforarmor_chestplate", () -> new MeliodasdanaforarmorItem.Chestplate());
	public static final RegistryObject<Item> MELIODASDANAFORARMOR_LEGGINGS = REGISTRY.register("meliodasdanaforarmor_leggings", () -> new MeliodasdanaforarmorItem.Leggings());
	public static final RegistryObject<Item> JERICHO_CHESTPLATE = REGISTRY.register("jericho_chestplate", () -> new JerichoItem.Chestplate());
	public static final RegistryObject<Item> JERICHO_LEGGINGS = REGISTRY.register("jericho_leggings", () -> new JerichoItem.Leggings());
	public static final RegistryObject<Item> HAWKS_SPAWN_EGG = REGISTRY.register("hawks_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.HAWKS, -1198672, -1337209, new Item.Properties()));
	public static final RegistryObject<Item> BELL_STAFF = REGISTRY.register("bell_staff", () -> new BellStaffItem());
	public static final RegistryObject<Item> WHIP = REGISTRY.register("whip", () -> new WhipItem());
	public static final RegistryObject<Item> CAPITALOFTHE_DEAD_BLOCK = block(CraftNoTaizaiModBlocks.CAPITALOFTHE_DEAD_BLOCK);
	public static final RegistryObject<Item> HYPER_RECOVERY = REGISTRY.register("hyper_recovery", () -> new HyperRecoveryItem());
	public static final RegistryObject<Item> BLACK_HOUND_SPAWN_EGG = REGISTRY.register("black_hound_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.BLACK_HOUND, -13942455, -3942848, new Item.Properties()));
	public static final RegistryObject<Item> SWORD_WOLF_SPAWN_EGG = REGISTRY.register("sword_wolf_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.SWORD_WOLF, -7521792, -4620800, new Item.Properties()));
	public static final RegistryObject<Item> APPLEPIE = REGISTRY.register("applepie", () -> new ApplepieItem());
	public static final RegistryObject<Item> DALE_ARMORED_SPAWN_EGG = REGISTRY.register("dale_armored_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.DALE_ARMORED, -6750055, -10092442, new Item.Properties()));
	public static final RegistryObject<Item> DALE_SEC_SPAWN_EGG = REGISTRY.register("dale_sec_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.DALE_SEC, -6749953, -6750055, new Item.Properties()));
	public static final RegistryObject<Item> DALEFINAL_SPAWN_EGG = REGISTRY.register("dalefinal_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.DALEFINAL, -3407668, -3407668, new Item.Properties()));
	public static final RegistryObject<Item> ELAINE_SPAWN_EGG = REGISTRY.register("elaine_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.ELAINE, -256, -1, new Item.Properties()));
	public static final RegistryObject<Item> BAKE_APPLE_PIE = REGISTRY.register("bake_apple_pie", () -> new BakeApplePieItem());
	public static final RegistryObject<Item> GUILA_ARMOR_CHESTPLATE = REGISTRY.register("guila_armor_chestplate", () -> new GuilaArmorItem.Chestplate());
	public static final RegistryObject<Item> GUILA_ARMOR_LEGGINGS = REGISTRY.register("guila_armor_leggings", () -> new GuilaArmorItem.Leggings());
	public static final RegistryObject<Item> FOUNTAIN_OF_YOUTH = REGISTRY.register("fountain_of_youth", () -> new FountainOfYouthItem());
	public static final RegistryObject<Item> KNIGHTARMOR_HELMET = REGISTRY.register("knightarmor_helmet", () -> new KnightarmorItem.Helmet());
	public static final RegistryObject<Item> KNIGHTARMOR_CHESTPLATE = REGISTRY.register("knightarmor_chestplate", () -> new KnightarmorItem.Chestplate());
	public static final RegistryObject<Item> KNIGHTARMOR_LEGGINGS = REGISTRY.register("knightarmor_leggings", () -> new KnightarmorItem.Leggings());
	public static final RegistryObject<Item> ROYALKNIGHT_HELMET = REGISTRY.register("royalknight_helmet", () -> new RoyalknightItem.Helmet());
	public static final RegistryObject<Item> ROYALKNIGHT_CHESTPLATE = REGISTRY.register("royalknight_chestplate", () -> new RoyalknightItem.Chestplate());
	public static final RegistryObject<Item> ROYALKNIGHT_LEGGINGS = REGISTRY.register("royalknight_leggings", () -> new RoyalknightItem.Leggings());
	public static final RegistryObject<Item> PERFECT_CUBE_ORB = REGISTRY.register("perfect_cube_orb", () -> new PerfectCubeOrbItem());
	public static final RegistryObject<Item> INSECT_SPAWN_EGG = REGISTRY.register("insect_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.INSECT, -3407668, -65281, new Item.Properties()));
	public static final RegistryObject<Item> FRIESIAARMOR_HELMET = REGISTRY.register("friesiaarmor_helmet", () -> new FriesiaarmorItem.Helmet());
	public static final RegistryObject<Item> FRIESIAARMOR_CHESTPLATE = REGISTRY.register("friesiaarmor_chestplate", () -> new FriesiaarmorItem.Chestplate());
	public static final RegistryObject<Item> FRIESIAARMOR_LEGGINGS = REGISTRY.register("friesiaarmor_leggings", () -> new FriesiaarmorItem.Leggings());
	public static final RegistryObject<Item> GOLGIUSARMOR_HELMET = REGISTRY.register("golgiusarmor_helmet", () -> new GolgiusarmorItem.Helmet());
	public static final RegistryObject<Item> GOLGIUSARMOR_CHESTPLATE = REGISTRY.register("golgiusarmor_chestplate", () -> new GolgiusarmorItem.Chestplate());
	public static final RegistryObject<Item> GOLGIUSARMOR_LEGGINGS = REGISTRY.register("golgiusarmor_leggings", () -> new GolgiusarmorItem.Leggings());
	public static final RegistryObject<Item> PERFECT_CUBE = block(CraftNoTaizaiModBlocks.PERFECT_CUBE);
	public static final RegistryObject<Item> BAR_DOOR = doubleBlock(CraftNoTaizaiModBlocks.BAR_DOOR);
	public static final RegistryObject<Item> HAY_BALE_ROOF = block(CraftNoTaizaiModBlocks.HAY_BALE_ROOF);
	public static final RegistryObject<Item> AREA_GROUND = block(CraftNoTaizaiModBlocks.AREA_GROUND);
	public static final RegistryObject<Item> AREAWOOD = block(CraftNoTaizaiModBlocks.AREAWOOD);
	public static final RegistryObject<Item> AREAFENCE = block(CraftNoTaizaiModBlocks.AREAFENCE);
	public static final RegistryObject<Item> AREA_SLAB = block(CraftNoTaizaiModBlocks.AREA_SLAB);
	public static final RegistryObject<Item> AREA_WOOD_SLAB = block(CraftNoTaizaiModBlocks.AREA_WOOD_SLAB);
	public static final RegistryObject<Item> GRAY_DEMON_SPAWN_EGG = REGISTRY.register("gray_demon_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GRAY_DEMON, -13213395, -12752844, new Item.Properties()));
	public static final RegistryObject<Item> EMPTY_NEEDLE = REGISTRY.register("empty_needle", () -> new EmptyNeedleItem());
	public static final RegistryObject<Item> GRAY_DEMON_BLOOD_NEEDLE = REGISTRY.register("gray_demon_blood_needle", () -> new GrayDemonBloodNeedleItem());
	public static final RegistryObject<Item> NEEDLE = REGISTRY.register("needle", () -> new NeedleItem());
	public static final RegistryObject<Item> HIDE_AND_SEEK_SPAWN_EGG = REGISTRY.register("hide_and_seek_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.HIDE_AND_SEEK, -12882822, -10076326, new Item.Properties()));
	public static final RegistryObject<Item> VINE_SPAWN_EGG = REGISTRY.register("vine_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.VINE, -13423595, -14278384, new Item.Properties()));
	public static final RegistryObject<Item> FIGHTING_AREA_SPAWN_EGG = REGISTRY.register("fighting_area_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.FIGHTING_AREA, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> TALA_VILLAGE_FLOWER = block(CraftNoTaizaiModBlocks.TALA_VILLAGE_FLOWER);
	public static final RegistryObject<Item> LUIGI_SPAWN_EGG = REGISTRY.register("luigi_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.LUIGI, -6737152, -26368, new Item.Properties()));
	public static final RegistryObject<Item> CAPITAL_OF_THE_DEAD_GROUND_BLOCK = block(CraftNoTaizaiModBlocks.CAPITAL_OF_THE_DEAD_GROUND_BLOCK);
	public static final RegistryObject<Item> CAPITAL_OF_THE_DEAD_GROUND = block(CraftNoTaizaiModBlocks.CAPITAL_OF_THE_DEAD_GROUND);
	public static final RegistryObject<Item> SLEEPING_FOREST_WOOD = block(CraftNoTaizaiModBlocks.SLEEPING_FOREST_WOOD);
	public static final RegistryObject<Item> SLEEPING_FOREST_SLAB = block(CraftNoTaizaiModBlocks.SLEEPING_FOREST_SLAB);
	public static final RegistryObject<Item> SLEEPING_FOREST_STAIR = block(CraftNoTaizaiModBlocks.SLEEPING_FOREST_STAIR);
	public static final RegistryObject<Item> TYRANT_DRAGON_SPAWN_EGG = REGISTRY.register("tyrant_dragon_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.TYRANT_DRAGON, -65536, -6750208, new Item.Properties()));
	public static final RegistryObject<Item> TYRANT_DRAGON_MEAT = REGISTRY.register("tyrant_dragon_meat", () -> new TyrantDragonMeatItem());
	public static final RegistryObject<Item> MUTILATOR_RABBITS_SPAWN_EGG = REGISTRY.register("mutilator_rabbits_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.MUTILATOR_RABBITS, -12031644, -5985126, new Item.Properties()));
	public static final RegistryObject<Item> ANGLE_CURE_SPAWN_EGG = REGISTRY.register("angle_cure_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.ANGLE_CURE, -11134398, -9417208, new Item.Properties()));
	public static final RegistryObject<Item> DUSK_BISON_1_SPAWN_EGG = REGISTRY.register("dusk_bison_1_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.DUSK_BISON_1, -3381760, -52429, new Item.Properties()));
	public static final RegistryObject<Item> CARBON_STEEL = REGISTRY.register("carbon_steel", () -> new CarbonSteelItem());
	public static final RegistryObject<Item> BULLET_SQUALL_SPAWN_EGG = REGISTRY.register("bullet_squall_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.BULLET_SQUALL, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> RANK = REGISTRY.register("rank", () -> new RankItem());
	public static final RegistryObject<Item> JERICHO_DEMON_FORM_SPAWN_EGG = REGISTRY.register("jericho_demon_form_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.JERICHO_DEMON_FORM, -6736897, -39322, new Item.Properties()));
	public static final RegistryObject<Item> TROLL_SPAWN_EGG = REGISTRY.register("troll_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.TROLL, -10040320, -16738048, new Item.Properties()));
	public static final RegistryObject<Item> KULUMIL_SPAWN_EGG = REGISTRY.register("kulumil_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.KULUMIL, -1, -52225, new Item.Properties()));
	public static final RegistryObject<Item> PUORA_SPAWN_EGG = REGISTRY.register("puora_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.PUORA, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> EARTH_CRAWLER_SPAWN_EGG = REGISTRY.register("earth_crawler_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.EARTH_CRAWLER, -13615322, -14997738, new Item.Properties()));
	public static final RegistryObject<Item> CHAIN_EXPLOSION_V_2_SPAWN_EGG = REGISTRY.register("chain_explosion_v_2_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.CHAIN_EXPLOSION_V_2, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> MAGIC_SCROLL = REGISTRY.register("magic_scroll", () -> new MagicScrollItem());
	public static final RegistryObject<Item> CLAY_DRAGON_SPAWN_EGG = REGISTRY.register("clay_dragon_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.CLAY_DRAGON, -10040320, -10092493, new Item.Properties()));
	public static final RegistryObject<Item> FAIRY_TREES_LOG = block(CraftNoTaizaiModBlocks.FAIRY_TREES_LOG);
	public static final RegistryObject<Item> FAIRY_KING_LOG = block(CraftNoTaizaiModBlocks.FAIRY_KING_LOG);
	public static final RegistryObject<Item> FAIRY_KING_LEAVE = block(CraftNoTaizaiModBlocks.FAIRY_KING_LEAVE);
	public static final RegistryObject<Item> MURAMO_DEMON_FORM_SPAWN_EGG = REGISTRY.register("muramo_demon_form_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.MURAMO_DEMON_FORM, -16737844, -13395457, new Item.Properties()));
	public static final RegistryObject<Item> ANDRE_DEMON_FORM_SPAWN_EGG = REGISTRY.register("andre_demon_form_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.ANDRE_DEMON_FORM, -3355648, -3355648, new Item.Properties()));
	public static final RegistryObject<Item> BOW = REGISTRY.register("bow", () -> new BowItem());
	public static final RegistryObject<Item> ACID_TWOWER_MOB_SPAWN_EGG = REGISTRY.register("acid_twower_mob_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.ACID_TWOWER_MOB, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> MURAMO_ARMOR_HELMET = REGISTRY.register("muramo_armor_helmet", () -> new MuramoArmorItem.Helmet());
	public static final RegistryObject<Item> MURAMO_ARMOR_CHESTPLATE = REGISTRY.register("muramo_armor_chestplate", () -> new MuramoArmorItem.Chestplate());
	public static final RegistryObject<Item> MURAMO_ARMOR_LEGGINGS = REGISTRY.register("muramo_armor_leggings", () -> new MuramoArmorItem.Leggings());
	public static final RegistryObject<Item> ANDRE_ARMOR_CHESTPLATE = REGISTRY.register("andre_armor_chestplate", () -> new AndreArmorItem.Chestplate());
	public static final RegistryObject<Item> ANDRE_ARMOR_LEGGINGS = REGISTRY.register("andre_armor_leggings", () -> new AndreArmorItem.Leggings());
	public static final RegistryObject<Item> PARADA_ARMOR_HELMET = REGISTRY.register("parada_armor_helmet", () -> new ParadaArmorItem.Helmet());
	public static final RegistryObject<Item> PARADA_ARMOR_CHESTPLATE = REGISTRY.register("parada_armor_chestplate", () -> new ParadaArmorItem.Chestplate());
	public static final RegistryObject<Item> PARADA_ARMOR_LEGGINGS = REGISTRY.register("parada_armor_leggings", () -> new ParadaArmorItem.Leggings());
	public static final RegistryObject<Item> SOLDIER_ARMOR_HELMET = REGISTRY.register("soldier_armor_helmet", () -> new SoldierArmorItem.Helmet());
	public static final RegistryObject<Item> SOLDIER_ARMOR_CHESTPLATE = REGISTRY.register("soldier_armor_chestplate", () -> new SoldierArmorItem.Chestplate());
	public static final RegistryObject<Item> SOLDIER_ARMOR_LEGGINGS = REGISTRY.register("soldier_armor_leggings", () -> new SoldierArmorItem.Leggings());
	public static final RegistryObject<Item> TWIGO_ARMOR_CHESTPLATE = REGISTRY.register("twigo_armor_chestplate", () -> new TwigoArmorItem.Chestplate());
	public static final RegistryObject<Item> TWIGO_ARMOR_LEGGINGS = REGISTRY.register("twigo_armor_leggings", () -> new TwigoArmorItem.Leggings());
	public static final RegistryObject<Item> RUIN_ARMOR_HELMET = REGISTRY.register("ruin_armor_helmet", () -> new RuinArmorItem.Helmet());
	public static final RegistryObject<Item> RUIN_ARMOR_CHESTPLATE = REGISTRY.register("ruin_armor_chestplate", () -> new RuinArmorItem.Chestplate());
	public static final RegistryObject<Item> RUIN_ARMOR_LEGGINGS = REGISTRY.register("ruin_armor_leggings", () -> new RuinArmorItem.Leggings());
	public static final RegistryObject<Item> GUILA_ARMOR_2_CHESTPLATE = REGISTRY.register("guila_armor_2_chestplate", () -> new GuilaArmor2Item.Chestplate());
	public static final RegistryObject<Item> GUILA_ARMOR_2_LEGGINGS = REGISTRY.register("guila_armor_2_leggings", () -> new GuilaArmor2Item.Leggings());
	public static final RegistryObject<Item> HOWZER_ARMOR_OUTFIT_CHESTPLATE = REGISTRY.register("howzer_armor_outfit_chestplate", () -> new HowzerArmorOutfitItem.Chestplate());
	public static final RegistryObject<Item> HOWZER_ARMOR_OUTFIT_LEGGINGS = REGISTRY.register("howzer_armor_outfit_leggings", () -> new HowzerArmorOutfitItem.Leggings());
	public static final RegistryObject<Item> CAIN_ARMOR_CHESTPLATE = REGISTRY.register("cain_armor_chestplate", () -> new CainArmorItem.Chestplate());
	public static final RegistryObject<Item> CAIN_ARMOR_LEGGINGS = REGISTRY.register("cain_armor_leggings", () -> new CainArmorItem.Leggings());
	public static final RegistryObject<Item> FAIRY_HELBRAM_ARMOR_CHESTPLATE = REGISTRY.register("fairy_helbram_armor_chestplate", () -> new FairyHelbramArmorItem.Chestplate());
	public static final RegistryObject<Item> FAIRY_HELBRAM_ARMOR_LEGGINGS = REGISTRY.register("fairy_helbram_armor_leggings", () -> new FairyHelbramArmorItem.Leggings());
	public static final RegistryObject<Item> GREEN_KNIGHT_ARMOR_HELMET = REGISTRY.register("green_knight_armor_helmet", () -> new GreenKnightArmorItem.Helmet());
	public static final RegistryObject<Item> GREEN_KNIGHT_ARMOR_CHESTPLATE = REGISTRY.register("green_knight_armor_chestplate", () -> new GreenKnightArmorItem.Chestplate());
	public static final RegistryObject<Item> GREEN_KNIGHT_ARMOR_LEGGINGS = REGISTRY.register("green_knight_armor_leggings", () -> new GreenKnightArmorItem.Leggings());
	public static final RegistryObject<Item> RED_KNIGHT_ARMOR_HELMET = REGISTRY.register("red_knight_armor_helmet", () -> new RedKnightArmorItem.Helmet());
	public static final RegistryObject<Item> RED_KNIGHT_ARMOR_CHESTPLATE = REGISTRY.register("red_knight_armor_chestplate", () -> new RedKnightArmorItem.Chestplate());
	public static final RegistryObject<Item> RED_KNIGHT_ARMOR_LEGGINGS = REGISTRY.register("red_knight_armor_leggings", () -> new RedKnightArmorItem.Leggings());
	public static final RegistryObject<Item> DREYFUS_ARMOR_CHESTPLATE = REGISTRY.register("dreyfus_armor_chestplate", () -> new DreyfusArmorItem.Chestplate());
	public static final RegistryObject<Item> DREYFUS_ARMOR_LEGGINGS = REGISTRY.register("dreyfus_armor_leggings", () -> new DreyfusArmorItem.Leggings());
	public static final RegistryObject<Item> HENDRICKSON_ARMOR_CHESTPLATE = REGISTRY.register("hendrickson_armor_chestplate", () -> new HendricksonArmorItem.Chestplate());
	public static final RegistryObject<Item> HENDRICKSON_ARMOR_LEGGINGS = REGISTRY.register("hendrickson_armor_leggings", () -> new HendricksonArmorItem.Leggings());
	public static final RegistryObject<Item> HUGO_ARMOR_HELMET = REGISTRY.register("hugo_armor_helmet", () -> new HugoArmorItem.Helmet());
	public static final RegistryObject<Item> HUGO_ARMOR_CHESTPLATE = REGISTRY.register("hugo_armor_chestplate", () -> new HugoArmorItem.Chestplate());
	public static final RegistryObject<Item> HUGO_ARMOR_LEGGINGS = REGISTRY.register("hugo_armor_leggings", () -> new HugoArmorItem.Leggings());
	public static final RegistryObject<Item> JILLIAN_ARMOR_CHESTPLATE = REGISTRY.register("jillian_armor_chestplate", () -> new JillianArmorItem.Chestplate());
	public static final RegistryObject<Item> JILLIAN_ARMOR_LEGGINGS = REGISTRY.register("jillian_armor_leggings", () -> new JillianArmorItem.Leggings());
	public static final RegistryObject<Item> SIMON_ARMOR_CHESTPLATE = REGISTRY.register("simon_armor_chestplate", () -> new SimonArmorItem.Chestplate());
	public static final RegistryObject<Item> SIMON_ARMOR_LEGGINGS = REGISTRY.register("simon_armor_leggings", () -> new SimonArmorItem.Leggings());
	public static final RegistryObject<Item> WEINHEIDT_ARMOR_CHESTPLATE = REGISTRY.register("weinheidt_armor_chestplate", () -> new WeinheidtArmorItem.Chestplate());
	public static final RegistryObject<Item> WEINHEIDT_ARMOR_LEGGINGS = REGISTRY.register("weinheidt_armor_leggings", () -> new WeinheidtArmorItem.Leggings());
	public static final RegistryObject<Item> VIVIAN_ARMOR_HELMET = REGISTRY.register("vivian_armor_helmet", () -> new VivianArmorItem.Helmet());
	public static final RegistryObject<Item> VIVIAN_ARMOR_CHESTPLATE = REGISTRY.register("vivian_armor_chestplate", () -> new VivianArmorItem.Chestplate());
	public static final RegistryObject<Item> VIVIAN_ARMOR_LEGGINGS = REGISTRY.register("vivian_armor_leggings", () -> new VivianArmorItem.Leggings());
	public static final RegistryObject<Item> GUSTAF_ARMOR_HELMET = REGISTRY.register("gustaf_armor_helmet", () -> new GustafArmorItem.Helmet());
	public static final RegistryObject<Item> GUSTAF_ARMOR_CHESTPLATE = REGISTRY.register("gustaf_armor_chestplate", () -> new GustafArmorItem.Chestplate());
	public static final RegistryObject<Item> GUSTAF_ARMOR_LEGGINGS = REGISTRY.register("gustaf_armor_leggings", () -> new GustafArmorItem.Leggings());
	public static final RegistryObject<Item> HEAT_FORK = REGISTRY.register("heat_fork", () -> new HeatForkItem());
	public static final RegistryObject<Item> EARTH_CRAWLER_TAIL = REGISTRY.register("earth_crawler_tail", () -> new EarthCrawlerTailItem());
	public static final RegistryObject<Item> ANGLE_CURE_MEAT = REGISTRY.register("angle_cure_meat", () -> new AngleCureMeatItem());
	public static final RegistryObject<Item> COOKED_ANGLE_MEAT = REGISTRY.register("cooked_angle_meat", () -> new CookedAngleMeatItem());
	public static final RegistryObject<Item> EARTH_CRAWLER_TAIL_COOKED = REGISTRY.register("earth_crawler_tail_cooked", () -> new EarthCrawlerTailCookedItem());
	public static final RegistryObject<Item> TYRANT_DRAGON_COOKED_MEAT = REGISTRY.register("tyrant_dragon_cooked_meat", () -> new TyrantDragonCookedMeatItem());
	public static final RegistryObject<Item> EARTH_GOLEM_SPAWN_EGG = REGISTRY.register("earth_golem_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.EARTH_GOLEM, -13290187, -11513776, new Item.Properties()));
	public static final RegistryObject<Item> COFFIN_OF_ETERNAL_DARKNESS = REGISTRY.register("coffin_of_eternal_darkness", () -> new CoffinOfEternalDarknessItem());
	public static final RegistryObject<Item> FRAGMENT_OF_ETERNAL_DARKNESS = REGISTRY.register("fragment_of_eternal_darkness", () -> new FragmentOfEternalDarknessItem());
	public static final RegistryObject<Item> FRAGMENT_OF_ETERNAL_DARKNESS_2 = REGISTRY.register("fragment_of_eternal_darkness_2", () -> new FragmentOfEternalDarkness2Item());
	public static final RegistryObject<Item> FRAGMENT_OF_ETERNAL_DARKNESS_3 = REGISTRY.register("fragment_of_eternal_darkness_3", () -> new FragmentOfEternalDarkness3Item());
	public static final RegistryObject<Item> MINIMUM_TABLETS = REGISTRY.register("minimum_tablets", () -> new MinimumTabletsItem());
	public static final RegistryObject<Item> PHYSICAL_CLONE_SPAWN_EGG = REGISTRY.register("physical_clone_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.PHYSICAL_CLONE, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> GUARDIAN_TRUE_SPIRT_SPEAR_SPAWN_EGG = REGISTRY.register("guardian_true_spirt_spear_spawn_egg",
			() -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GUARDIAN_TRUE_SPIRT_SPEAR, -13382656, -10027264, new Item.Properties()));
	public static final RegistryObject<Item> KEG = block(CraftNoTaizaiModBlocks.KEG);
	public static final RegistryObject<Item> EMPTY_MUG = REGISTRY.register("empty_mug", () -> new EmptyMugItem());
	public static final RegistryObject<Item> EMPTY_MUG_BLOCK = block(CraftNoTaizaiModBlocks.EMPTY_MUG_BLOCK);
	public static final RegistryObject<Item> STAGE_ONE_AGAVE = block(CraftNoTaizaiModBlocks.STAGE_ONE_AGAVE);
	public static final RegistryObject<Item> MUG_ALE = REGISTRY.register("mug_ale", () -> new MugAleItem());
	public static final RegistryObject<Item> ALE_RED_MUG = block(CraftNoTaizaiModBlocks.ALE_RED_MUG);
	public static final RegistryObject<Item> STAGE_TWO_AGAVE = block(CraftNoTaizaiModBlocks.STAGE_TWO_AGAVE);
	public static final RegistryObject<Item> LAST_STAGE_AGAVE = block(CraftNoTaizaiModBlocks.LAST_STAGE_AGAVE);
	public static final RegistryObject<Item> AGAVE_SEEDS = REGISTRY.register("agave_seeds", () -> new AgaveSeedsItem());
	public static final RegistryObject<Item> AGAVE = REGISTRY.register("agave", () -> new AgaveItem());
	public static final RegistryObject<Item> GLOW_MUG = REGISTRY.register("glow_mug", () -> new GlowMugItem());
	public static final RegistryObject<Item> GLOW_MUG_BLOCK = block(CraftNoTaizaiModBlocks.GLOW_MUG_BLOCK);
	public static final RegistryObject<Item> BEER_MUG = REGISTRY.register("beer_mug", () -> new BeerMugItem());
	public static final RegistryObject<Item> BEER_MUG_BLOCK = block(CraftNoTaizaiModBlocks.BEER_MUG_BLOCK);
	public static final RegistryObject<Item> FAIRY_KING_LEAVES = block(CraftNoTaizaiModBlocks.FAIRY_KING_LEAVES);
	public static final RegistryObject<Item> CHICKEN_MATANGO_MUSH_ROOM = REGISTRY.register("chicken_matango_mush_room", () -> new ChickenMatangoMushRoomItem());
	public static final RegistryObject<Item> GODDASS_ORE = block(CraftNoTaizaiModBlocks.GODDASS_ORE);
	public static final RegistryObject<Item> GODDESS_AMBER = REGISTRY.register("goddess_amber", () -> new GoddessAmberItem());
	public static final RegistryObject<Item> GODDESS_AMBER_SHARD = REGISTRY.register("goddess_amber_shard", () -> new GoddessAmberShardItem());
	public static final RegistryObject<Item> FAIRY_TREE_SAPLINGS = block(CraftNoTaizaiModBlocks.FAIRY_TREE_SAPLINGS);
	public static final RegistryObject<Item> FAIRY_TREE_WOOD = block(CraftNoTaizaiModBlocks.FAIRY_TREE_WOOD);
	public static final RegistryObject<Item> FAIRY_TREE_FENCE = block(CraftNoTaizaiModBlocks.FAIRY_TREE_FENCE);
	public static final RegistryObject<Item> FAIRY_TREE_STAIRES = block(CraftNoTaizaiModBlocks.FAIRY_TREE_STAIRES);
	public static final RegistryObject<Item> FAIRY_TREE_SLAB = block(CraftNoTaizaiModBlocks.FAIRY_TREE_SLAB);
	public static final RegistryObject<Item> BASTE_DUNGEON_WALLS = block(CraftNoTaizaiModBlocks.BASTE_DUNGEON_WALLS);
	public static final RegistryObject<Item> BASTE_DUNGEON_ROOF = block(CraftNoTaizaiModBlocks.BASTE_DUNGEON_ROOF);
	public static final RegistryObject<Item> BEAR_ICON = REGISTRY.register("bear_icon", () -> new BearIconItem());
	public static final RegistryObject<Item> SERPENT_ICON = REGISTRY.register("serpent_icon", () -> new SerpentIconItem());
	public static final RegistryObject<Item> FOX_ICON = REGISTRY.register("fox_icon", () -> new FoxIconItem());
	public static final RegistryObject<Item> GOAT_ICON = REGISTRY.register("goat_icon", () -> new GoatIconItem());
	public static final RegistryObject<Item> PIG_ICON = REGISTRY.register("pig_icon", () -> new PigIconItem());
	public static final RegistryObject<Item> DRAGON_ICON = REGISTRY.register("dragon_icon", () -> new DragonIconItem());
	public static final RegistryObject<Item> TWIGO_ANIMATED_SPAWN_EGG = REGISTRY.register("twigo_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.TWIGO_ANIMATED, -4868683, -2665902, new Item.Properties()));
	public static final RegistryObject<Item> GRAY_DEMON_ENTITY_SPAWN_EGG = REGISTRY.register("gray_demon_entity_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GRAY_DEMON_ENTITY, -9607313, -11120296, new Item.Properties()));
	public static final RegistryObject<Item> GIL_THUNDER_ANIMATED_SPAWN_EGG = REGISTRY.register("gil_thunder_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GIL_THUNDER_ANIMATED, -746073, -13811095, new Item.Properties()));
	public static final RegistryObject<Item> GOLGIUS_ANIMATED_SPAWN_EGG = REGISTRY.register("golgius_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GOLGIUS_ANIMATED, -13618371, -8681583, new Item.Properties()));
	public static final RegistryObject<Item> DIANE_ANIMATED_SPAWN_EGG = REGISTRY.register("diane_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.DIANE_ANIMATED, -2256067, -13227743, new Item.Properties()));
	public static final RegistryObject<Item> RUIN_ANIMATED_SPAWN_EGG = REGISTRY.register("ruin_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.RUIN_ANIMATED, -5596817, -13613481, new Item.Properties()));
	public static final RegistryObject<Item> FRIESIA_ANIMATED_SPAWN_EGG = REGISTRY.register("friesia_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.FRIESIA_ANIMATED, -7193517, -13793641, new Item.Properties()));
	public static final RegistryObject<Item> GUILA_ANIMATED_SPAWN_EGG = REGISTRY.register("guila_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GUILA_ANIMATED, -3355444, -39169, new Item.Properties()));
	public static final RegistryObject<Item> TAIZOO_ANIMATED_SPAWN_EGG = REGISTRY.register("taizoo_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.TAIZOO_ANIMATED, -16751236, -8840137, new Item.Properties()));
	public static final RegistryObject<Item> GRIAMORE_ANIMATED_SPAWN_EGG = REGISTRY.register("griamore_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GRIAMORE_ANIMATED, -278639, -16514044, new Item.Properties()));
	public static final RegistryObject<Item> HOWZER_ANIMATED_SPAWN_EGG = REGISTRY.register("howzer_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.HOWZER_ANIMATED, -12624858, -10404509, new Item.Properties()));
	public static final RegistryObject<Item> CAIN_BARZAD_ANIMATED_SPAWN_EGG = REGISTRY.register("cain_barzad_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.CAIN_BARZAD_ANIMATED, -3381103, -4865920, new Item.Properties()));
	public static final RegistryObject<Item> STORY_BAN_ANIMATED_SPAWN_EGG = REGISTRY.register("story_ban_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.STORY_BAN_ANIMATED, -65485, -3407872, new Item.Properties()));
	public static final RegistryObject<Item> JERICHO_ANIMATED_SPAWN_EGG = REGISTRY.register("jericho_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.JERICHO_ANIMATED, -2126950, -2638897, new Item.Properties()));
	public static final RegistryObject<Item> GUILA_DEMONANIMATED_SPAWN_EGG = REGISTRY.register("guila_demonanimated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GUILA_DEMONANIMATED, -6723841, -13421773, new Item.Properties()));
	public static final RegistryObject<Item> HELBREM_ANIMATED_SPAWN_EGG = REGISTRY.register("helbrem_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.HELBREM_ANIMATED, -10027213, -26368, new Item.Properties()));
	public static final RegistryObject<Item> GIL_THUNDER_ANIMATED_2_SPAWN_EGG = REGISTRY.register("gil_thunder_animated_2_spawn_egg",
			() -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GIL_THUNDER_ANIMATED_2, -39169, -13408513, new Item.Properties()));
	public static final RegistryObject<Item> RED_KNIGHT_ANIMATED_SPAWN_EGG = REGISTRY.register("red_knight_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.RED_KNIGHT_ANIMATED, -6750157, -3407872, new Item.Properties()));
	public static final RegistryObject<Item> GREEN_KNIGHT_ANIMATED_SPAWN_EGG = REGISTRY.register("green_knight_animated_spawn_egg",
			() -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GREEN_KNIGHT_ANIMATED, -10040320, -13395712, new Item.Properties()));
	public static final RegistryObject<Item> DREYFUS_ANIMATED_SPAWN_EGG = REGISTRY.register("dreyfus_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.DREYFUS_ANIMATED, -6750208, -256, new Item.Properties()));
	public static final RegistryObject<Item> FAIRY_HELBREM_ANIMATED_SPAWN_EGG = REGISTRY.register("fairy_helbrem_animated_spawn_egg",
			() -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.FAIRY_HELBREM_ANIMATED, -256, -13369600, new Item.Properties()));
	public static final RegistryObject<Item> DEAD_HELBRAMANIMATED_SPAWN_EGG = REGISTRY.register("dead_helbramanimated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.DEAD_HELBRAMANIMATED, -13369549, -6684928, new Item.Properties()));
	public static final RegistryObject<Item> VIVIAN_ANIMATED_SPAWN_EGG = REGISTRY.register("vivian_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.VIVIAN_ANIMATED, -65536, -6710887, new Item.Properties()));
	public static final RegistryObject<Item> ROYAL_GURARD_ANIMATED_SPAWN_EGG = REGISTRY.register("royal_gurard_animated_spawn_egg",
			() -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.ROYAL_GURARD_ANIMATED, -6710887, -3355444, new Item.Properties()));
	public static final RegistryObject<Item> ROYAL_GUARD_ANIMATED_SPAWN_EGG = REGISTRY.register("royal_guard_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.ROYAL_GUARD_ANIMATED, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> SOLDIER_ANIMATED_SPAWN_EGG = REGISTRY.register("soldier_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.SOLDIER_ANIMATED, -6845575, -6447715, new Item.Properties()));
	public static final RegistryObject<Item> HENDRICKSON_ANIMATED_SPAWN_EGG = REGISTRY.register("hendrickson_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.HENDRICKSON_ANIMATED, -10235084, -4210494, new Item.Properties()));
	public static final RegistryObject<Item> STORY_BAN_2_ANIMATED_SPAWN_EGG = REGISTRY.register("story_ban_2_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.STORY_BAN_2_ANIMATED, -3407872, -65536, new Item.Properties()));
	public static final RegistryObject<Item> PARADA_ANIMATED_SPAWN_EGG = REGISTRY.register("parada_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.PARADA_ANIMATED, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> DEMON_HENDRICKSON_ANIMATED_SPAWN_EGG = REGISTRY.register("demon_hendrickson_animated_spawn_egg",
			() -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.DEMON_HENDRICKSON_ANIMATED, -15204323, -4210494, new Item.Properties()));
	public static final RegistryObject<Item> GRAY_DEMON_HENDRICKSON_ANIMATED_SPAWN_EGG = REGISTRY.register("gray_demon_hendrickson_animated_spawn_egg",
			() -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GRAY_DEMON_HENDRICKSON_ANIMATED, -5196599, -15459284, new Item.Properties()));
	public static final RegistryObject<Item> ANDRE_ANIMATED_SPAWN_EGG = REGISTRY.register("andre_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.ANDRE_ANIMATED, -4609702, -7301220, new Item.Properties()));
	public static final RegistryObject<Item> MURAMO_ANIMATED_SPAWN_EGG = REGISTRY.register("muramo_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.MURAMO_ANIMATED, -16750951, -16750849, new Item.Properties()));
	public static final RegistryObject<Item> DUMBLEBBAS_ANIMATED_SPAWN_EGG = REGISTRY.register("dumblebbas_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.DUMBLEBBAS_ANIMATED, -13159, -26266, new Item.Properties()));
	public static final RegistryObject<Item> WEINHEIDT_ANIMATED_SPAWN_EGG = REGISTRY.register("weinheidt_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.WEINHEIDT_ANIMATED, -3355648, -16764007, new Item.Properties()));
	public static final RegistryObject<Item> HUGO_ANIMATED_SPAWN_EGG = REGISTRY.register("hugo_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.HUGO_ANIMATED, -6710887, -16750900, new Item.Properties()));
	public static final RegistryObject<Item> JILLIAN_ANIMATED_SPAWN_EGG = REGISTRY.register("jillian_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.JILLIAN_ANIMATED, -1, -65536, new Item.Properties()));
	public static final RegistryObject<Item> SIMON_ANIMATED_SPAWN_EGG = REGISTRY.register("simon_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.SIMON_ANIMATED, -7849178, -1, new Item.Properties()));
	public static final RegistryObject<Item> BAN_BOSS_ANIMATED_SPAWN_EGG = REGISTRY.register("ban_boss_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.BAN_BOSS_ANIMATED, -3407821, -6750208, new Item.Properties()));
	public static final RegistryObject<Item> SLADER_ANIMATED_SPAWN_EGG = REGISTRY.register("slader_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.SLADER_ANIMATED, -3570793, -13289657, new Item.Properties()));
	public static final RegistryObject<Item> GUSTAF_ANIMATED_SPAWN_EGG = REGISTRY.register("gustaf_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GUSTAF_ANIMATED, -11958857, -11958857, new Item.Properties()));
	public static final RegistryObject<Item> DIANE_BOSS_ANIMATED_SPAWN_EGG = REGISTRY.register("diane_boss_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.DIANE_BOSS_ANIMATED, -1464994, -13466469, new Item.Properties()));
	public static final RegistryObject<Item> GOWTHER_BOSS_ANIMATED_SPAWN_EGG = REGISTRY.register("gowther_boss_animated_spawn_egg",
			() -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GOWTHER_BOSS_ANIMATED, -4869956, -4088878, new Item.Properties()));
	public static final RegistryObject<Item> KING_BOSS_ANIMATED_SPAWN_EGG = REGISTRY.register("king_boss_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.KING_BOSS_ANIMATED, -26368, -16711681, new Item.Properties()));
	public static final RegistryObject<Item> MELIODAS_BOSS_ANIMATED_SPAWN_EGG = REGISTRY.register("meliodas_boss_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.MELIODAS_BOSS_ANIMATED, -1, -256, new Item.Properties()));
	public static final RegistryObject<Item> MERLIN_BOSS_ANIMATED_SPAWN_EGG = REGISTRY.register("merlin_boss_animated_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.MERLIN_BOSS_ANIMATED, -10092442, -6750055, new Item.Properties()));
	public static final RegistryObject<Item> WICKED_BITE_SPAWN_EGG = REGISTRY.register("wicked_bite_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.WICKED_BITE, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> EMPTYORB = REGISTRY.register("emptyorb", () -> new EmptyorbItem());
	public static final RegistryObject<Item> BALORS_MAGICAL_EYE_HELMET = REGISTRY.register("balors_magical_eye_helmet", () -> new BalorsMagicalEyeItem.Helmet());
	public static final RegistryObject<Item> DEATH_THORN_SPAWN_EGG = REGISTRY.register("death_thorn_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.DEATH_THORN, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> BASQUIAS_GUARDIAN_SPAWN_EGG = REGISTRY.register("basquias_guardian_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.BASQUIAS_GUARDIAN, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> HOLY_TREE_SHARD = REGISTRY.register("holy_tree_shard", () -> new HolyTreeShardItem());
	public static final RegistryObject<Item> HOLY_TREE_ORE = block(CraftNoTaizaiModBlocks.HOLY_TREE_ORE);
	public static final RegistryObject<Item> GIGA_PICK_SPAWN_EGG = REGISTRY.register("giga_pick_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GIGA_PICK, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> GIGA_FALL_SPAWN_EGG = REGISTRY.register("giga_fall_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GIGA_FALL, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> GIGA_CRUSH_SPAWN_EGG = REGISTRY.register("giga_crush_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GIGA_CRUSH, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> BLACK_OUT_SPAWN_EGG = REGISTRY.register("black_out_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.BLACK_OUT, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> SUN_FLOWER_TRUE_SPIRT_SPEAR_SPAWN_EGG = REGISTRY.register("sun_flower_true_spirt_spear_spawn_egg",
			() -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.SUN_FLOWER_TRUE_SPIRT_SPEAR, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> MOON_ROSE_SPAWN_EGG = REGISTRY.register("moon_rose_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.MOON_ROSE, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> LUME_ORB = REGISTRY.register("lume_orb", () -> new LumeOrbItem());
	public static final RegistryObject<Item> CHAOS_FLOOR = block(CraftNoTaizaiModBlocks.CHAOS_FLOOR);
	public static final RegistryObject<Item> CHAOS_WALL = block(CraftNoTaizaiModBlocks.CHAOS_WALL);
	public static final RegistryObject<Item> BOAR_HAT_OUTFIT_CHESTPLATE = REGISTRY.register("boar_hat_outfit_chestplate", () -> new BoarHatOutfitItem.Chestplate());
	public static final RegistryObject<Item> BOAR_HAT_OUTFIT_LEGGINGS = REGISTRY.register("boar_hat_outfit_leggings", () -> new BoarHatOutfitItem.Leggings());
	public static final RegistryObject<Item> HELL_GATE_RED_DEMONS_SPAWN_EGG = REGISTRY.register("hell_gate_red_demons_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.HELL_GATE_RED_DEMONS, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> JUMANJU_ENTITY_SPAWN_EGG = REGISTRY.register("jumanju_entity_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.JUMANJU_ENTITY, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> COCOON_OF_DARKNESS_SPAWN_EGG = REGISTRY.register("cocoon_of_darkness_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.COCOON_OF_DARKNESS, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> LOW_TIER_SOULS = REGISTRY.register("low_tier_souls", () -> new LowTierSoulsItem());
	public static final RegistryObject<Item> MID_TIER_SOULS = REGISTRY.register("mid_tier_souls", () -> new MidTierSoulsItem());
	public static final RegistryObject<Item> HIGH_TIER_SOULS = REGISTRY.register("high_tier_souls", () -> new HighTierSoulsItem());
	public static final RegistryObject<Item> GERHEADE_SPAWN_EGG = REGISTRY.register("gerheade_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GERHEADE, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> SERVANT_SPAWN_EGG = REGISTRY.register("servant_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.SERVANT, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> MARMAS_SPAWN_EGG = REGISTRY.register("marmas_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.MARMAS, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> AEAL_HEAL_SPAWN_EGG = REGISTRY.register("aeal_heal_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.AEAL_HEAL, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> TROLL_EAR = REGISTRY.register("troll_ear", () -> new TrollEarItem());
	public static final RegistryObject<Item> CURVED_SWORD = REGISTRY.register("curved_sword", () -> new CurvedSwordItem());
	public static final RegistryObject<Item> HALBERT = REGISTRY.register("halbert", () -> new HalbertItem());
	public static final RegistryObject<Item> HENDRIKSON_SWORD = REGISTRY.register("hendrikson_sword", () -> new HendriksonSwordItem());
	public static final RegistryObject<Item> DEMON_KING_SWORD = REGISTRY.register("demon_king_sword", () -> new DemonKingSwordItem());
	public static final RegistryObject<Item> DREYFUS_SWORD = REGISTRY.register("dreyfus_sword", () -> new DreyfusSwordItem());
	public static final RegistryObject<Item> KATANA = REGISTRY.register("katana", () -> new KatanaItem());
	public static final RegistryObject<Item> SCYTHE = REGISTRY.register("scythe", () -> new ScytheItem());
	public static final RegistryObject<Item> JERICHO_SWORD = REGISTRY.register("jericho_sword", () -> new JerichoSwordItem());
	public static final RegistryObject<Item> GOLGIUS_SWORD = REGISTRY.register("golgius_sword", () -> new GolgiusSwordItem());
	public static final RegistryObject<Item> TWIGOSWORD = REGISTRY.register("twigosword", () -> new TwigoswordItem());
	public static final RegistryObject<Item> SPIRALEDLANCE = REGISTRY.register("spiraledlance", () -> new SpiraledlanceItem());
	public static final RegistryObject<Item> RAPIER = REGISTRY.register("rapier", () -> new RapierItem());
	public static final RegistryObject<Item> GIL_THUNDER_SWORD = REGISTRY.register("gil_thunder_sword", () -> new GilThunderSwordItem());
	public static final RegistryObject<Item> HELBRUMSWORD = REGISTRY.register("helbrumsword", () -> new HelbrumswordItem());
	public static final RegistryObject<Item> SEQUENCE = REGISTRY.register("sequence", () -> new SequenceItem());
	public static final RegistryObject<Item> SAW_SWORD = REGISTRY.register("saw_sword", () -> new SawSwordItem());
	public static final RegistryObject<Item> AXE_2 = REGISTRY.register("axe_2", () -> new Axe2Item());
	public static final RegistryObject<Item> SAW_BLADE = REGISTRY.register("saw_blade", () -> new SawBladeItem());
	public static final RegistryObject<Item> LONG_AXE = REGISTRY.register("long_axe", () -> new LongAxeItem());
	public static final RegistryObject<Item> GUARD_SPEAR = REGISTRY.register("guard_spear", () -> new GuardSpearItem());
	public static final RegistryObject<Item> HOLY_STAFF_COURE_CHOUSE = REGISTRY.register("holy_staff_coure_chouse", () -> new HolyStaffCoureChouseItem());
	public static final RegistryObject<Item> HORN_OF_CERNUNOS_SPAWN_EGG = REGISTRY.register("horn_of_cernunos_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.HORN_OF_CERNUNOS, -29953, -38401, new Item.Properties()));
	public static final RegistryObject<Item> DOGEDO_SPAWN_EGG = REGISTRY.register("dogedo_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.DOGEDO, -9822, -12681421, new Item.Properties()));
	public static final RegistryObject<Item> GOWTHER_STORY_1_SPAWN_EGG = REGISTRY.register("gowther_story_1_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GOWTHER_STORY_1, -65281, -10066177, new Item.Properties()));
	public static final RegistryObject<Item> ALBION_SPAWN_EGG = REGISTRY.register("albion_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.ALBION, -1842194, -11576014, new Item.Properties()));
	public static final RegistryObject<Item> ALBION_FAT_SPAWN_EGG = REGISTRY.register("albion_fat_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.ALBION_FAT, -1842194, -11576014, new Item.Properties()));
	public static final RegistryObject<Item> TALL_ALBION_SPAWN_EGG = REGISTRY.register("tall_albion_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.TALL_ALBION, -3683904, -12761051, new Item.Properties()));
	public static final RegistryObject<Item> PURGATORY_BLOCK = block(CraftNoTaizaiModBlocks.PURGATORY_BLOCK);
	public static final RegistryObject<Item> ALBION_TALL_SPAWN_EGG = REGISTRY.register("albion_tall_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.ALBION_TALL, -3683904, -12761051, new Item.Properties()));
	public static final RegistryObject<Item> PURGATORY_SLAB = block(CraftNoTaizaiModBlocks.PURGATORY_SLAB);
	public static final RegistryObject<Item> PURGATORY_STAIR = block(CraftNoTaizaiModBlocks.PURGATORY_STAIR);
	public static final RegistryObject<Item> GODDESS_BLESS_ENTITY_SPAWN_EGG = REGISTRY.register("goddess_bless_entity_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GODDESS_BLESS_ENTITY, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> SWORD_WOLF_FUR = REGISTRY.register("sword_wolf_fur", () -> new SwordWolfFurItem());
	public static final RegistryObject<Item> MONSTER_BLOCK = REGISTRY.register("monster_block", () -> new MonsterBlockItem());
	public static final RegistryObject<Item> PURGATORY_BRICK = block(CraftNoTaizaiModBlocks.PURGATORY_BRICK);
	public static final RegistryObject<Item> PURGATORY_BRICK_SLAB = block(CraftNoTaizaiModBlocks.PURGATORY_BRICK_SLAB);
	public static final RegistryObject<Item> PURGATORY_BRICK_STAIR = block(CraftNoTaizaiModBlocks.PURGATORY_BRICK_STAIR);
	public static final RegistryObject<Item> MERLIN_ARMOR_CHEST_PLATE_HELMET = REGISTRY.register("merlin_armor_chest_plate_helmet", () -> new MerlinArmorChestPlateItem.Helmet());
	public static final RegistryObject<Item> MERLIN_ARMOR_CHEST_PLATE_CHESTPLATE = REGISTRY.register("merlin_armor_chest_plate_chestplate", () -> new MerlinArmorChestPlateItem.Chestplate());
	public static final RegistryObject<Item> MERLIN_ARMOR_CHEST_PLATE_LEGGINGS = REGISTRY.register("merlin_armor_chest_plate_leggings", () -> new MerlinArmorChestPlateItem.Leggings());
	public static final RegistryObject<Item> BAN_ARMOR_HELMET = REGISTRY.register("ban_armor_helmet", () -> new BanArmorItem.Helmet());
	public static final RegistryObject<Item> BAN_ARMOR_CHESTPLATE = REGISTRY.register("ban_armor_chestplate", () -> new BanArmorItem.Chestplate());
	public static final RegistryObject<Item> BAN_ARMOR_LEGGINGS = REGISTRY.register("ban_armor_leggings", () -> new BanArmorItem.Leggings());
	public static final RegistryObject<Item> DIANE_ARMOR_HELMET = REGISTRY.register("diane_armor_helmet", () -> new DianeArmorItem.Helmet());
	public static final RegistryObject<Item> DIANE_ARMOR_CHESTPLATE = REGISTRY.register("diane_armor_chestplate", () -> new DianeArmorItem.Chestplate());
	public static final RegistryObject<Item> DIANE_ARMOR_LEGGINGS = REGISTRY.register("diane_armor_leggings", () -> new DianeArmorItem.Leggings());
	public static final RegistryObject<Item> ESCANOR_ARMOR_HELMET = REGISTRY.register("escanor_armor_helmet", () -> new EscanorArmorItem.Helmet());
	public static final RegistryObject<Item> ESCANOR_ARMOR_CHESTPLATE = REGISTRY.register("escanor_armor_chestplate", () -> new EscanorArmorItem.Chestplate());
	public static final RegistryObject<Item> ESCANOR_ARMOR_LEGGINGS = REGISTRY.register("escanor_armor_leggings", () -> new EscanorArmorItem.Leggings());
	public static final RegistryObject<Item> GOWTHER_ARMOR_HELMET = REGISTRY.register("gowther_armor_helmet", () -> new GowtherArmorItem.Helmet());
	public static final RegistryObject<Item> GOWTHER_ARMOR_CHESTPLATE = REGISTRY.register("gowther_armor_chestplate", () -> new GowtherArmorItem.Chestplate());
	public static final RegistryObject<Item> GOWTHER_ARMOR_LEGGINGS = REGISTRY.register("gowther_armor_leggings", () -> new GowtherArmorItem.Leggings());
	public static final RegistryObject<Item> KINGS_ARMOR_HELMET = REGISTRY.register("kings_armor_helmet", () -> new KingsArmorItem.Helmet());
	public static final RegistryObject<Item> KINGS_ARMOR_CHESTPLATE = REGISTRY.register("kings_armor_chestplate", () -> new KingsArmorItem.Chestplate());
	public static final RegistryObject<Item> KINGS_ARMOR_LEGGINGS = REGISTRY.register("kings_armor_leggings", () -> new KingsArmorItem.Leggings());
	public static final RegistryObject<Item> MELIODAS_ARMOR_HELMET = REGISTRY.register("meliodas_armor_helmet", () -> new MeliodasArmorItem.Helmet());
	public static final RegistryObject<Item> MELIODAS_ARMOR_CHESTPLATE = REGISTRY.register("meliodas_armor_chestplate", () -> new MeliodasArmorItem.Chestplate());
	public static final RegistryObject<Item> MELIODAS_ARMOR_LEGGINGS = REGISTRY.register("meliodas_armor_leggings", () -> new MeliodasArmorItem.Leggings());
	public static final RegistryObject<Item> DEMON_KING_SPAWN_EGG = REGISTRY.register("demon_king_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.DEMON_KING, -15264234, -3407668, new Item.Properties()));
	public static final RegistryObject<Item> PEACE_AMULET_CHESTPLATE = REGISTRY.register("peace_amulet_chestplate", () -> new PeaceAmuletItem.Chestplate());
	public static final RegistryObject<Item> SMALL_HAWKS_SPAWN_EGG = REGISTRY.register("small_hawks_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.SMALL_HAWKS, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> GALAND_SPAWN_EGG = REGISTRY.register("galand_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GALAND, -8448202, -13754301, new Item.Properties()));
	public static final RegistryObject<Item> MATRONA_SPAWN_EGG = REGISTRY.register("matrona_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.MATRONA, -9654873, -12353377, new Item.Properties()));
	public static final RegistryObject<Item> DOUBLE_SIDED_SPEAR = REGISTRY.register("double_sided_spear", () -> new DoubleSidedSpearItem());
	public static final RegistryObject<Item> SLEEPING_FOREST_DIRT = block(CraftNoTaizaiModBlocks.SLEEPING_FOREST_DIRT);
	public static final RegistryObject<Item> TELEPORTATION_ORB = REGISTRY.register("teleportation_orb", () -> new TeleportationOrbItem());
	public static final RegistryObject<Item> TOWER_OF_TRIALS = block(CraftNoTaizaiModBlocks.TOWER_OF_TRIALS);
	public static final RegistryObject<Item> CAVE_OF_TRAINING = block(CraftNoTaizaiModBlocks.CAVE_OF_TRAINING);
	public static final RegistryObject<Item> SIDE_MOUNTAIN = block(CraftNoTaizaiModBlocks.SIDE_MOUNTAIN);
	public static final RegistryObject<Item> THEO_SPAWN_EGG = REGISTRY.register("theo_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.THEO, -12302779, -10079906, new Item.Properties()));
	public static final RegistryObject<Item> JENNA_SPAWN_EGG = REGISTRY.register("jenna_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.JENNA, -1914531, -7070414, new Item.Properties()));
	public static final RegistryObject<Item> ZANERI_SPAWN_EGG = REGISTRY.register("zaneri_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.ZANERI, -1, -3837556, new Item.Properties()));
	public static final RegistryObject<Item> BASQUIAS = REGISTRY.register("basquias", () -> new BasquiasItem());
	public static final RegistryObject<Item> DIAMOND_TOWER_SPAWN_EGG = REGISTRY.register("diamond_tower_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.DIAMOND_TOWER, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> ESCANOR_BOSS_SPAWN_EGG = REGISTRY.register("escanor_boss_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.ESCANOR_BOSS, -12627156, -2118785, new Item.Properties()));
	public static final RegistryObject<Item> CLOVER_SPAWN_EGG = REGISTRY.register("clover_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.CLOVER, -14542563, -150017, new Item.Properties()));
	public static final RegistryObject<Item> ISTAR_PORTAL_BLOCK = block(CraftNoTaizaiModBlocks.ISTAR_PORTAL_BLOCK);
	public static final RegistryObject<Item> BRITANNIA_COINS = REGISTRY.register("britannia_coins", () -> new BritanniaCoinsItem());
	public static final RegistryObject<Item> CANNON_ENTITY_SPAWN_EGG = REGISTRY.register("cannon_entity_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.CANNON_ENTITY, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> SLEEPING_FOREST_PLANK = block(CraftNoTaizaiModBlocks.SLEEPING_FOREST_PLANK);
	public static final RegistryObject<Item> SEVEN_DEADLY_SINS_OPENING = REGISTRY.register("seven_deadly_sins_opening", () -> new SevenDeadlySinsOpeningItem());
	public static final RegistryObject<Item> GLOXINA_BOSS_SPAWN_EGG = REGISTRY.register("gloxina_boss_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GLOXINA_BOSS, -4965284, -10778489, new Item.Properties()));
	public static final RegistryObject<Item> MOSS_DRAGON_SPAWN_EGG = REGISTRY.register("moss_dragon_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.MOSS_DRAGON, -12169686, -13421028, new Item.Properties()));
	public static final RegistryObject<Item> TYRANT_DRAGON_CAVE_SPAWN_EGG = REGISTRY.register("tyrant_dragon_cave_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.TYRANT_DRAGON_CAVE, -65536, -6750208, new Item.Properties()));
	public static final RegistryObject<Item> ANAON_SPAWN_EGG = REGISTRY.register("anaon_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.ANAON, -14935267, -15987700, new Item.Properties()));
	public static final RegistryObject<Item> OMINOUS_NEBULA_ENITIY_SPAWN_EGG = REGISTRY.register("ominous_nebula_enitiy_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.OMINOUS_NEBULA_ENITIY, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> MELIODAS_BOAR_HAT_CHESTPLATE = REGISTRY.register("meliodas_boar_hat_chestplate", () -> new MeliodasBoarHatItem.Chestplate());
	public static final RegistryObject<Item> MELIODAS_BOAR_HAT_LEGGINGS = REGISTRY.register("meliodas_boar_hat_leggings", () -> new MeliodasBoarHatItem.Leggings());
	public static final RegistryObject<Item> GOWTHER_ARMOR_S_2_CHESTPLATE = REGISTRY.register("gowther_armor_s_2_chestplate", () -> new GowtherArmorS2Item.Chestplate());
	public static final RegistryObject<Item> GOWTHER_ARMOR_S_2_LEGGINGS = REGISTRY.register("gowther_armor_s_2_leggings", () -> new GowtherArmorS2Item.Leggings());
	public static final RegistryObject<Item> KING_STORY_1_SPAWN_EGG = REGISTRY.register("king_story_1_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.KING_STORY_1, -138288, -5804990, new Item.Properties()));
	public static final RegistryObject<Item> GALAND_STORY_2_SPAWN_EGG = REGISTRY.register("galand_story_2_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GALAND_STORY_2, -8448202, -13754301, new Item.Properties()));
	public static final RegistryObject<Item> BAN_ARMOR_S_2_HELMET = REGISTRY.register("ban_armor_s_2_helmet", () -> new BanArmorS2Item.Helmet());
	public static final RegistryObject<Item> BAN_ARMOR_S_2_CHESTPLATE = REGISTRY.register("ban_armor_s_2_chestplate", () -> new BanArmorS2Item.Chestplate());
	public static final RegistryObject<Item> BAN_ARMOR_S_2_LEGGINGS = REGISTRY.register("ban_armor_s_2_leggings", () -> new BanArmorS2Item.Leggings());
	public static final RegistryObject<Item> ELAINE_STORY_SPAWN_EGG = REGISTRY.register("elaine_story_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.ELAINE_STORY, -14212306, -8181720, new Item.Properties()));
	public static final RegistryObject<Item> GALAND_OVER_SPAWN_EGG = REGISTRY.register("galand_over_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.GALAND_OVER, -8448202, -13754301, new Item.Properties()));
	public static final RegistryObject<Item> RHITTA_BLOCK = REGISTRY.register(CraftNoTaizaiModBlocks.RHITTA_BLOCK.getId().getPath(), () -> new RhittaBlockDisplayItem(CraftNoTaizaiModBlocks.RHITTA_BLOCK.get(), new Item.Properties()));
	public static final RegistryObject<Item> RE_ROLL_MAGIC = REGISTRY.register("re_roll_magic", () -> new ReRollMagicItem());
	public static final RegistryObject<Item> CIDER_MUG_BLOCK = block(CraftNoTaizaiModBlocks.CIDER_MUG_BLOCK);
	public static final RegistryObject<Item> CIDER_MUG = REGISTRY.register("cider_mug", () -> new CiderMugItem());
	public static final RegistryObject<Item> REAPER_SCYTHE = REGISTRY.register("reaper_scythe", () -> new ReaperScytheItem());
	public static final RegistryObject<Item> REAPER_SCYTHE_ENTITY_SPAWN_EGG = REGISTRY.register("reaper_scythe_entity_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.REAPER_SCYTHE_ENTITY, -1, -1, new Item.Properties()));
	public static final RegistryObject<Item> FLYING_SAUCER = REGISTRY.register("flying_saucer", () -> new FlyingSaucerItem());
	public static final RegistryObject<Item> COOK_TROLL_EAR = REGISTRY.register("cook_troll_ear", () -> new CookTrollEarItem());
	public static final RegistryObject<Item> STAFF_OF_IMPRISONMENT = REGISTRY.register("staff_of_imprisonment", () -> new StaffOfImprisonmentItem());
	public static final RegistryObject<Item> DUBS_SPAWN_EGG = REGISTRY.register("dubs_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.DUBS, -6170673, -3565712, new Item.Properties()));
	public static final RegistryObject<Item> BLUE_DEMON_SPAWN_EGG = REGISTRY.register("blue_demon_spawn_egg", () -> new ForgeSpawnEggItem(CraftNoTaizaiModEntities.BLUE_DEMON, -10579532, -9095101, new Item.Properties()));
	public static final RegistryObject<Item> ESCANOR_TAVERN_HELMET = REGISTRY.register("escanor_tavern_helmet", () -> new EscanorTavernItem.Helmet());
	public static final RegistryObject<Item> ESCANOR_TAVERN_CHESTPLATE = REGISTRY.register("escanor_tavern_chestplate", () -> new EscanorTavernItem.Chestplate());
	public static final RegistryObject<Item> ESCANOR_TAVERN_LEGGINGS = REGISTRY.register("escanor_tavern_leggings", () -> new EscanorTavernItem.Leggings());
	public static final RegistryObject<Item> ELAINE_ARMOR_CHESTPLATE = REGISTRY.register("elaine_armor_chestplate", () -> new ElaineArmorItem.Chestplate());
	public static final RegistryObject<Item> ELAINE_ARMOR_LEGGINGS = REGISTRY.register("elaine_armor_leggings", () -> new ElaineArmorItem.Leggings());
	public static final RegistryObject<Item> ZELDRIS_SWORD = REGISTRY.register("zeldris_sword", () -> new ZeldrisSwordItem());
	public static final RegistryObject<Item> REPOSE_ICON = REGISTRY.register("repose_icon", () -> new ReposeIconItem());

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}

	private static RegistryObject<Item> doubleBlock(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new DoubleHighBlockItem(block.get(), new Item.Properties()));
	}

	@SubscribeEvent
	public static void clientLoad(FMLClientSetupEvent event) {
		event.enqueueWork(() -> {
			ItemProperties.register(FLYING_SAUCER.get(), new ResourceLocation("blocking"), ItemProperties.getProperty(Items.SHIELD, new ResourceLocation("blocking")));
		});
	}
}
